FROM ubuntu:22.04

USER root
SHELL ["/bin/bash", "-e", "-o", "pipefail", "-c"]

ARG CERTDOMAIN=scenescape.intel.com

ENV DEBIAN_FRONTEND=noninteractive

COPY docker/requirements-buildtime.txt /tmp

RUN apt-get update && apt-get install -y --no-install-recommends \
        bzip2 \
        curl \
        g++ \
        libboost-python-dev \
        libegl1 \
        libeigen3-dev \
        libgl1 \
        libglib2.0 \
        libgtest-dev \
        make \
        pybind11-dev \
        python-is-python3 \
        python3-dev \
        python3-pip \
        python3-scipy \
        sudo \
    && pip3 install --upgrade --no-cache-dir \
        --extra-index-url https://download.pytorch.org/whl/cpu \
        -r /tmp/requirements-buildtime.txt

# Build scene_common
COPY scene_common /tmp/
RUN : \
    ; cd tmp/ \
    ; pip install --no-cache-dir . \
    ; make -C fast_geometry -j $(nproc) all install \
    ;
